export const REQUEST_FETCH_PEOPLE = 'REQUEST_FETCH_PEOPLE';
export const RECEIVE_FETCH_PEOPLE = 'RECEIVE_FETCH_PEOPLE';
export const REQUEST_FETCH_VEHICLE= 'REQUEST_FETCH_VEHICLE';
export const RECIEVE_FETCH_VEHICLE = 'RECIEVE_FETCH_VEHICLE';
